In [34]:
# Import all necessary libraries.
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, roc_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#x_train = ['send us your password',
#    'send us your review',
#    'review your password',
#    'review us',
#    'send your password',
#    'send us your account']

#y_train = [0, 1, 1, 0, 0, 0]

#x_test = ['review the contract']
#y_test = [0]

In [13]:
#x_train = ['congratulations you are selected',
#           'congrats you won lottery',
#           'travel for free',
#           'selected for credit card',
#           'very good',
#           'good night',
#           'lottery']

#y_train = [1, 0, 0, 0, 1, 1, 0]
#y_train = ['ham', 'spam', 'spam', 'spam', 'ham', 'ham', 'spam']

#x_test = ['you won lottery"']

In [14]:
#x_train = np.array(['free great offer if you join, a great offer for free!',
#          'great offer for free delivery',
#          'uber is promoting a great offer for free',
#          'try uber for free for your 1st ride',
#          'earn your uber 10 credit for free by applying for the uber visa credit card',
#          'uber receipt'])

# spam: 0
# ham: 1
#y_train = np.array([0, 0, 0, 1, 1, 1])

#y_train = np.array(['spam','spam','spam','ham','ham','ham'])

#x_test = np.array(['Moonnight Trial', 'Limited offer: Free & Great Deal'])

In [67]:
x_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])

y_train = np.array(['china','china','china','not china'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

## BernoulliNB

In [68]:
# Instantiate a CountVectorizer object.
vect = CountVectorizer(binary=True)

In [69]:
# Fit and transform X_train into x_train_dtm (document-term matrices - dtm).
x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [70]:
# Transform X_test into X_test_dtm.
x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())

[[0 1 1 0 0 1]]


In [27]:
# Instantiate a Bernoulli Naive Bayes model.
model = BernoulliNB(binarize=None)

In [28]:
# train the model using X_train_dtm
model.fit(x_train_dtm, y_train)

BernoulliNB(alpha=1.0, binarize=None, class_prior=None, fit_prior=True)

In [29]:
y_pred_class = model.predict(x_test_dtm)

In [30]:
print(y_pred_class)

['not china']


In [31]:
print(model.predict_proba(x_test_dtm))

[[0.19106679 0.80893321]]


## Explicação
O vetor de teste é idêntico ao quarto vetor de treinamento, o qual pertence à classe 'not-china', e portanto, ele é consequentemente classificado como tal.

## MultinomialNB

In [57]:
x_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])

y_train = np.array(['china','china','china','not china'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

In [58]:
# Instantiate a CountVectorizer object.
vect = CountVectorizer()

In [59]:
# Fit and transform X_train into x_train_dtm (document-term matrices - dtm).
x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [60]:
# Transform X_test into X_test_dtm.
x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())

[[0 3 1 0 0 1]]


In [61]:
# Instantiate a Multinomial Naive Bayes model.
model = MultinomialNB()

In [62]:
# train the model using X_train_dtm
model.fit(x_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [63]:
y_pred_class = model.predict(x_test_dtm)

In [64]:
print(y_pred_class)

['china']


In [65]:
print(model.predict_proba(x_test_dtm))

[[0.68975861 0.31024139]]


## Explicação
O motivo dessa classificação é que as três ocorrências do indicador positivo 'chinese' no vetor de test superam (tem maior peso) do que as ocorrências dos dois indicadores negativos 'japan' e 'tokyo'

## References

[1] https://nlp.stanford.edu/IR-book/html/htmledition/naive-bayes-text-classification-1.html

[2] https://web.stanford.edu/~jurafsky/slp3/slides/7_NB.pdf